apiVersion: v1
kind: Config
clusters:
- cluster:
    server: https://127.0.0.1:6443
    certificate-authority: /home/developer/.minikube/ca.crt
  name: minikube
contexts:
- context:
    cluster: minikube
    namespace: pipelines
    user: minikube
  name: pipelines-context
current-context: pipelines-context
users:
- name: minikube
  user:
    client-certificate: /home/developer/.minikube/profiles/minikube/client.crt
    client-key: /home/developer/.minikube/profiles/minikube/client.key
