apiVersion: v1
kind: Config
clusters:
- cluster:
    server: https://your-k8s-api-server:6443
    certificate-authority-data: <CA_DATA>
  name: pipelines-cluster
contexts:
- context:
    cluster: pipelines-cluster
    namespace: pipelines
    user: pipelines-user
  name: pipelines-context
current-context: pipelines-context
users:
- name: pipelines-user
  user:
    token: <PIPELINES_USER_TOKEN>
