apiVersion: v1
kind: Config
clusters:
- cluster:
    server: https://your-k8s-api-server:6443
    certificate-authority-data: <CA_DATA>
  name: jenkins-cluster
contexts:
- context:
    cluster: jenkins-cluster
    namespace: jenkins
    user: jenkins-user
  name: jenkins-context
current-context: jenkins-context
users:
- name: jenkins-user
  user:
    token: <JENKINS_USER_TOKEN>
